"""Shared tool schemas for MCP, OpenAI function-calling, and HTTP agents.

Keep these definitions in one place so Cursor / Claude Desktop / Copilot /
custom agents all see the same contract.

This module is the stable import path; the implementation lives in
``artificial_emotions.agent_tools_pkg`` (schemas → handlers → registry →
mcp_resources).
"""

from __future__ import annotations

from artificial_emotions.agent_tools_pkg import (
    ANNOTATE_EPISTEMIC_SCHEMA,
    COMPARE_PROFILES_SCHEMA,
    CONSTITUTION_COMPARE_SCHEMA,
    CRITIQUE_BRIEF_SCHEMA,
    CROSS_MODEL_VOTE_SCHEMA,
    DECOMPOSE_SCHEMA,
    ELICIT_HELPERS_SCHEMA,
    EMOTION_CATALOG_SCHEMA,
    EMOTION_PACK_SCHEMA,
    HANDLERS,
    IDEA_GRAPH_SCHEMA,
    LIST_DOMAINS_SCHEMA,
    LIST_EPISTEMIC_CUES_SCHEMA,
    LIST_PROFILES_SCHEMA,
    MIX_EMOTIONS_SCHEMA,
    PROVOKE_SCHEMA,
    RANK_SCHEMA,
    SOUNDNESS_PASS_SCHEMA,
    SURPRISE_WORKSHEET_SCHEMA,
    TOOL_SPECS,
    VOI_WORKSHEET_SCHEMA,
    ToolHandler,
    dispatch_tool,
    handle_annotate_epistemic,
    handle_compare_profiles,
    handle_constitution_compare,
    handle_critique_brief,
    handle_cross_model_vote,
    handle_decompose_question,
    handle_elicit_helpers,
    handle_emotion_catalog,
    handle_emotion_pack,
    handle_idea_graph,
    handle_list_domains,
    handle_list_epistemic_cues,
    handle_list_profiles,
    handle_mix_emotions,
    handle_provoke_curiosity,
    handle_rank_unknowns,
    handle_soundness_pass,
    handle_surprise_worksheet,
    handle_voi_worksheet,
    mcp_resource_list,
    mcp_resource_read,
    mcp_tool_list,
    mcp_tool_tiers,
    openai_tools,
    resolve_mcp_tier,
    tools_as_json,
)

__all__ = [
    "ANNOTATE_EPISTEMIC_SCHEMA",
    "COMPARE_PROFILES_SCHEMA",
    "CONSTITUTION_COMPARE_SCHEMA",
    "CRITIQUE_BRIEF_SCHEMA",
    "CROSS_MODEL_VOTE_SCHEMA",
    "DECOMPOSE_SCHEMA",
    "ELICIT_HELPERS_SCHEMA",
    "EMOTION_CATALOG_SCHEMA",
    "EMOTION_PACK_SCHEMA",
    "HANDLERS",
    "IDEA_GRAPH_SCHEMA",
    "LIST_DOMAINS_SCHEMA",
    "LIST_EPISTEMIC_CUES_SCHEMA",
    "LIST_PROFILES_SCHEMA",
    "MIX_EMOTIONS_SCHEMA",
    "PROVOKE_SCHEMA",
    "RANK_SCHEMA",
    "SOUNDNESS_PASS_SCHEMA",
    "SURPRISE_WORKSHEET_SCHEMA",
    "TOOL_SPECS",
    "ToolHandler",
    "VOI_WORKSHEET_SCHEMA",
    "dispatch_tool",
    "handle_annotate_epistemic",
    "handle_compare_profiles",
    "handle_constitution_compare",
    "handle_critique_brief",
    "handle_cross_model_vote",
    "handle_decompose_question",
    "handle_elicit_helpers",
    "handle_emotion_catalog",
    "handle_emotion_pack",
    "handle_idea_graph",
    "handle_list_domains",
    "handle_list_epistemic_cues",
    "handle_list_profiles",
    "handle_mix_emotions",
    "handle_provoke_curiosity",
    "handle_rank_unknowns",
    "handle_soundness_pass",
    "handle_surprise_worksheet",
    "handle_voi_worksheet",
    "mcp_resource_list",
    "mcp_resource_read",
    "mcp_tool_list",
    "mcp_tool_tiers",
    "openai_tools",
    "resolve_mcp_tier",
    "tools_as_json",
]
